channels:
- conda-forge
dependencies:
- gpaw >=20
- jupyter
- lammps >=2021.05.27
- lammps =*=*hf0e8f25_openmpi*
- nglview
- ipywidgets <8  # conflict with NGLview
- papermill
- seaborn
- sphinxdft >=3.0
- sphinxdft-data
- iprpy-data
- pyiron-data >=0.0.27
- sqsgenerator
- gpaw =23.9.1
