channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- aimsgb =1.1.0
- ase =3.24.0
- atomistics =0.1.34
- defusedxml =0.7.1
- h5py =3.12.1
- matplotlib-base =3.10.0
- mendeleev =0.19.0
- mp-api =0.45.1
- numpy =1.26.4
- pandas =2.2.3
- phonopy =2.34.1
- pint =0.24.4
- pyiron_base =0.10.11
- pyiron_snippets =0.1.4
- pylammpsmpi =0.2.27
- pyscal3 =3.2.7
- scikit-learn =1.6.1
- scipy =1.15.1
- seekpath =2.1.0
- spglib =2.5.0
- structuretoolkit =0.0.30
- pyxtal =0.6.2
- jupyter-book =1.0.0
