channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- aimsgb =1.1.0
- ase =3.27.0
- assyst =0.11.0
- atomistics =0.3.5
- defusedxml =0.7.1
- h5py =3.15.1
- matplotlib-base =3.10.8
- mendeleev =1.1.0
- mp-api =0.46.0
- numpy =2.3.5
- pandas =2.3.3
- phonopy =2.47.1
- pint =0.25.2
- pyiron_base =0.15.12
- pyiron_lammps =0.5.2
- pyiron_snippets =1.0.2
- pyiron_vasp =0.2.18
- pylammpsmpi =0.3.9
- pyscal3 =3.3.0
- scikit-learn =1.8.0
- scipy =1.16.3
- seekpath =2.2.1
- spglib =2.7.0
- structuretoolkit =0.0.39
- pyxtal =1.1.1
- jupyter-book =1.0.0
- sphinx_parser =0.1.6
- hatchling =1.28.0
- hatch-vcs =0.5.0
