channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- aimsgb =1.1.0
- ase =3.26.0
- assyst =0.9.0
- atomistics =0.3.3
- defusedxml =0.7.1
- h5py =3.15.1
- matplotlib-base =3.10.7
- mendeleev =1.1.0
- mp-api =0.45.13
- numpy =2.3.4
- pandas =2.3.3
- phonopy =2.44.0
- pint =0.25.2
- pyiron_base =0.15.9
- pyiron_lammps =0.4.9
- pyiron_snippets =1.0.2
- pyiron_vasp =0.2.15
- pylammpsmpi =0.3.6
- pyscal3 =3.3.0
- scikit-learn =1.7.2
- scipy =1.16.3
- seekpath =2.1.0
- spglib =2.6.0
- structuretoolkit =0.0.37
- pyxtal =1.1.1
- jupyter-book =1.0.0
- sphinx_parser =0.1.5
- hatchling =1.27.0
- hatch-vcs =0.5.0
