channels:
- conda-forge
dependencies:
- gpaw =24.1.0
- jupyter
- lammps =2024.02.07
- nglview
- ipywidgets
- papermill
- seaborn =0.13.2
- sphinxdft =3.1
- sphinxdft-data =0.0.1
- iprpy-data =2022.11.02
- pyiron-data =0.0.29
- sqsgenerator =0.3
