title: pyiron_atomistics
author: Jan Janssen
logo: images/pyiron-logo.png

execute:
  execute_notebooks           : off

repository:
  url                       : https://github.com/pyiron/pyiron_atomistics
html:
  use_repository_button: true

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  config:
    autosummary_generate: True
    templates_path: ['_templates']
