channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.26.0
- assyst =0.9.0
- atomistics =0.3.4
- defusedxml =0.7.1
- h5py =3.15.1
- matplotlib-base =3.10.7
- mendeleev =1.1.0
- mp-api =0.45.13
- numpy =2.3.5
- pandas =2.3.3
- phonopy =2.45.1
- pint =0.25.2
- pyiron_base =0.15.10
- pyiron_lammps =0.5.1
- pyiron_snippets =1.0.2
- pyiron_vasp =0.2.16
- pylammpsmpi =0.3.7
- pyscal3 =3.3.0
- scikit-learn =1.8.0
- scipy =1.16.3
- seekpath =2.1.0
- spglib =2.6.0
- structuretoolkit =0.0.38
- pyxtal =1.1.1
- pyiron-data =0.0.30
- sqsgenerator =0.3
- lammps =2024.08.29=*_openmpi_*
- iprpy-data =2022.11.02
- gpaw =25.6.0
- sphinx_parser =0.1.5
- sphinxdft =3.1
- sphinxdft-data =0.0.1
- nglview =3.1.2
- seaborn =0.13.2
- hatchling =1.28.0
- hatch-vcs =0.5.0
