channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.23.0
- atomistics =0.1.32
- defusedxml =0.7.1
- h5py =3.11.0
- matplotlib-base =3.9.2
- mendeleev =0.17.0
- mp-api =0.42.1
- numpy =2.1.0
- pandas =2.2.2
- phonopy =2.26.6
- pint =0.24.3
- pyiron_base =0.10.0
- pyiron_snippets =0.1.4
- pylammpsmpi =0.2.24
- pyscal3 =3.2.7
- scikit-learn =1.5.1
- scipy =1.14.1
- seekpath =2.1.0
- spglib =2.5.0
- structuretoolkit =0.0.28
- pyxtal =0.6.2
- pyiron-data =0.0.30
- sqsgenerator =0.3
- lammps =2024.06.27=*_openmpi_*
- iprpy-data =2022.11.02
- gpaw =24.6.0
- sphinxdft =3.1
- sphinxdft-data =0.0.1
- nglview =3.1.2
- seaborn =0.13.2
